export const EMAIL_VERIFY_REQUEST='EMAIL_VERIFY_REQUEST';
export const EMAIL_VERIFY_SUCCESS='EMAIL_VERIFY_SUCCESS';
export const EMAIL_VERIFY_FAILURE='EMAIL_VERIFY_FAILURE';

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';
